#!/bin/awk -f
function color(temp){
    if (temp < 39)
        return "#aaFF66"
    if (temp < 43)
        return "#CCFF33"
    if (temp < 50)
        return "#EEFF00"
    if (temp < 57)
        return "#FFCC00"
    if (temp < 64)
        return "#FF9900"
    if (temp < 71)
        return "#FF6600"
    if (temp < 78)
        return "#FF3300"
    if (temp < 85)
        return "#FF1100"
    # exit code 33 will turn background red
    exit 33
}
function apply_color(string, color){
    return sprintf("%{F%s}%s%{F-}", color,string);
    #return sprintf("<span color='%s'>%s</span>", color,string);
}
function color_temp(temp){
    return apply_color(temp, color(temp));
}
/^Core/ {
    gsub(/\.0°C/, "");
    gsub(/\+/, "");
    temp=$3;
    temps = sprintf("%s,%s", temps, color_temp(temp))
}
END {print substr(temps,2)};
