#!/bin/awk -f
function mount_format(mount){
    temp = mount
    if(temp){
        sub(/\/mnt\//, "@", temp)
        return temp
    }
    return "?"
}
/part/ && /^[^nvme0n1]/ {
    all = sprintf("%s|<small><sub>%s</sub></small><u>%s</u><small><sub>%s</sub></small>",all,mount_format($4),$1,$3)
}
END {print all};
