#!/bin/sh
case $BLOCK_BUTTON in
	1) notify-send "Memory hogs:" "$(ps axch -o %mem,cmd --sort=-%mem | head)" ;;
	3) notify-send "Memory module:" "- Shows Memory Used/Total
- Click to show memory hogs." ;;
esac

free -h | awk '/^Mem:/ {print $3 "/" $2}'
