#!/bin/sh
fd . yoav projects Desktop to-be-sorted org -t d \
    | sed 's|/|❭|g' \
    | rofi -dmenu -i -theme-str 'textbox-icon {str: "    ";} prompt {enabled: false;}' \
    | sed 's|❭|/|g' \
    | xargs -r -I % xdg-open "%"
