#!/bin/sh
cd ~ || exit 1
EXTS="-e pdf -e md -e markdown -e org -e epub -e doc -e docx -e mp4 -e mkv -e wmv -e webm -e m4v -e cbz -e djvu -e avi -e mscz" # -e jpg -e png
fd . -t f $EXTS \
    | bemenu --grab -p "Doc: "\
    | xargs -d '\n' -r xdg-open
