#!/usr/bin/env sh
# Copied from https://github.com/hlissner/dotfiles/tree/master/bin/rofi
rofi -show window \
     -show-icons \
     -theme-str 'textbox-icon {str: "    ";}
prompt {enabled: false;}
element {font: @text-mono-font;}'
