#!/bin/sh
alias \
	ka="nocorrect killall" \
	ls="ls -hN --group-directories-first" \
	diff="diff --color=auto" \
	config="/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME" \
	vim="nvim" \
	v="TERM=xterm-256color emacsclient -t -a \"\"" \
	ec="emacsclient" \
	sv="sk | xargs emacsclient -t -a \"\"" \
	ce="edit-config" \
	grep="grep --color=auto" \
	rand-bg="feh --randomize --bg-fill ~/.wallpapers/*" \
	idea="_JAVA_AWT_WM_NONREPARENTING=1 idea &" \
	n="nnn" \
	python="python3" \
	pip="pip3" \
	f="xdg-open" \
	sai="sudo apt install" \
	s="sudo" \
	doom="$HOME/.emacs.d/bin/doom"\
	rn="react-native"\


# SHORTCUTS
alias \
	y="cd ~/Dropbox/yoav/" \
	u="cd ~/Dropbox/yoav/uni/" \
	s="cd ~/Dropbox/yoav/school/" \
	d="cd ~/Desktop/" \
	D="cd ~/Downloads/" \
	t="cd ~/Downloads/Torrents/" \

# FUNCTIONS

# search in bash history, copy selected to clipboard
hs() {
	sort -ubi ~/.zsh_history | sk | xargs -r -I % printf "%" | xclip -selection clipboard
}

# get preformance info about processes, how much of my resources they used since
# startup
pinfo() {
	ps axch -o cmd,%cpu,%mem | sk --header "PROCESS                      CPU  MEM" >/dev/null
}

# Sum statistics about me flacs
musicinfo() {
	fd -t f -e flac | xargs -d '\n' soxi -D |
		awk '{a+=$0; tot+=1} END {print tot " songs, " a/(60*60) " hours of playback, average song length is " a/tot/60 " mins."}'
	echo "summing $(du -sh .)"
}

# Print only the important bit from xev, i.e key code number & name.
xevkeyinfo() {
	# From ArchWiki
	# https://wiki.archlinux.org/index.php/Keyboard_input#Identifying_keycodes_in_Xorg
	xev | awk -F'[ )]+' '/^KeyPress/ { a[NR+2] } NR in a { printf "%-3s %s\n", $5, $8 }'
}
