#!/bin/sh
alias \
	ka="nocorrect killall" \
	ls="ls -hN --group-directories-first --color=auto" \
	diff="diff --color=auto" \
	config="/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME" \
	vim="nvim" \
	v="emacsclient -t -a \"\"" \
	ec="emacsclient" \
	sv="sk | xargs emacsclient -t -a \"\"" \
	ce="edit-config" \
	grep="grep --color=auto" \
	rand-bg="feh --randomize --bg-fill ~/.wallpapers/*" \
	idea="_JAVA_AWT_WM_NONREPARENTING=1 idea &" \
	n="nnn" \
	python="python3" \
	f="xdg-open" \
	sai="sudo apt install" \
	s="sudo" \
	doom="EMACSLOADPATH=$GUIX_PROFILE/share/emacs/28.0.50/lisp:$GUIX_PROFILE/share/emacs/site-lisp $HOME/.config/emacs/bin/doom"\
	rn="react-native"\
	mpv="mpv --ytdl-raw-options='no-check-certificate='"



# SHORTCUTS
alias \
	y="cd ~/yoav/" \
	u="cd ~/yoav/uni/" \
	s="cd ~/yoav/school/" \
	d="cd ~/Desktop/" \
	t="cd ~/to-be-sorted/" \
	T="cd ~/to-be-sorted/Torrents/" \

# FUNCTIONS

# search in bash history, copy selected to clipboard
hs() {
	sort -ubi "$HISTFILE" | sk | xargs -r -I % printf "%" | xclip -selection clipboard
}

# get preformance info about processes, how much of my resources they used since
# startup
pinfo() {
	ps axch -o cmd,%cpu,%mem | sk --header "PROCESS                      CPU  MEM" >/dev/null
}

# Sum statistics about me flacs
musicinfo() {
	soxi -D **/*.flac |
		awk '{a+=$0; tot+=1} END {print tot " songs, " a/(60*60) " hours of playback, average song length is " a/tot/60 " mins."}'
	echo "summing $(du -sh .)"
}

# Print only the important bit from xev, i.e key code number & name.
xevkeyinfo() {
	# From ArchWiki
	# https://wiki.archlinux.org/index.php/Keyboard_input#Identifying_keycodes_in_Xorg
	xev | awk -F'[ )]+' '/^KeyPress/ { a[NR+2] } NR in a { printf "%-3s %s\n", $5, $8 }'
}
