#! /bin/sh

sxhkd &


bspc monitor HDMI1 -d 1 2 3 4
bspc monitor eDP1 -d 5 6 7 8

bspc config border_width         1
bspc config window_gap          12

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle 	 	 true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
#bspc rule -a $TERM state=pseudo_tiled

#polybar &
