#!/bin/sh

pgrep sxhkd || sxhkd -m 1 &

DESKS1='0 1 2 3'
DESKS2='4 5 6 7'

# Monitors
bspc monitor			-d $DESKS1
bspc monitor HDMI-1		-d $DESKS2
bspc monitor HDMI-1-1	-d $DESKS2
bspc monitor eDP1		-d $DESKS1
bspc monitor eDP-1		-d $DESKS1
bspc monitor eDP-1-1	-d $DESKS1
bspc config remove_disabled_monitors on
bspc config remove_unplugged_monitors on

# Gaps
## Basic config
bspc config border_width         1
bspc config window_gap           12
## No gap on single-window desktops
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true


# Colors
# this configurs bspwm to use the xcolor $2 as color $1
setXcolor(){
	xrdb -query | awk "/$2/ {print \$NF}" | xargs -r -I % bspc config $1 %
}
setXcolor normal_border_color color0 # black
bspc config focused_border_color '#aaaaaa'


# Desktop Rules
bspc rule -a Gimp				desktop='^8' state=floating follow=on
bspc rule -a Firefox			desktop='^2'
bspc rule -a Zathura			state=tiled
bspc rule -a Emacs				split_ratio=0.28 state=fullscreen border=off
bspc rule -a xst-256color		border=off
bspc rule -a Firefox			split_ratio=0.32
bspc rule -a feh				state=fullscreen
bspc rule -a 'Emacs:org*'		state=floating
bspc rule -a 'Emacs:scratch'	state=floating
#bspc rule -a St state=pseudo_tiled

# General Settings
bspc config directional_focus_tightness low
if ! pgrep lemonbar; then
	cd ~/desk/lemonbarc/ || exit
	./run.sh &
	cd ~ || exit
fi
