#!/bin/sh

# Guess what pdfs need optimizing by if their .log files exist
command -v optpdf >/dev/null && {
	echo "Optimizing"
	for log in *.log; do
		base="${log%.*}"
		[ -f "$base.pdf" ] && optpdf "$base.pdf"
	done
}

echo "Removing junk"
# normal latex compilation junk
rm -f *.aux *.auxlock *.fdb_latexmk *.fls *.xdv *.bbl *.brf *.blg *.log *.out *.synctex.gz *.fmt *.atfi *.dvi *.md5 *.dpth *.auxlock
# auctex junk
rm -rf .auctex-auto _region_*
