#!/bin/sh

if pgrep vlc; then # if playing from VLC, pause it
    dbus-send --type=method_call --dest=org.mpris.MediaPlayer2.vlc /org/mpris/MediaPlayer2   org.mpris.MediaPlayer2.Player.PlayPause
else # probably playing from mpd
    mpc toggle
fi
