#!/bin/sh

alias qdbus-vlc="qdbus org.mpris.MediaPlayer2.vlc /org/mpris/MediaPlayer2"

if pgrep vlc > /dev/null; then # if playing from VLC, pause it
    echo aoeu
    case "$1" in
        seek) qdbus-vlc org.mpris.MediaPlayer2.Player.Seek "$2";;
        toggle)
            # if mpd is playing then I probably want to pause IT and not vlc
            if mpc status | grep playing > /dev/null; then
                mpc -q toggle
            else
                qdbus-vlc org.mpris.MediaPlayer2.Player.PlayPause
            fi;;
        next) qdbus-vlc org.mpris.MediaPlayer2.Player.Next;;
        prev) qdbus-vlc org.mpris.MediaPlayer2.Player.Previous;;
    esac
else # probably playing from mpd
    case "$1" in
        seek) mpc -q seek "$2";;
        toggle|prev) mpc -q "$1";;
        next) mpc status | head -1 >> .config/mpd/skipped-songs
              mpc -q next;;
        copy) echo "https://www.youtube.com/results?search_query=$(mpc status | head -1 | sed 's/ /+/g')" \
            | xclip -sel clip;;
    esac
fi
