#!/bin/sh

alias qdbus-vlc="qdbus org.mpris.MediaPlayer2.vlc /org/mpris/MediaPlayer2"

if pgrep vlc > /dev/null; then # if playing from VLC, pause it
    case "$1" in
        seek) qdbus-vlc org.mpris.MediaPlayer2.Player.Seek "$2";;
        toggle)
            # if mpd is playing then I probably want to pause IT and not vlc
            if mpc status | grep playing > /dev/null; then
                mpc toggle
            else
                qdbus-vlc org.mpris.MediaPlayer2.Player.PlayPause
            fi;;
        next) qdbus-vlc org.mpris.MediaPlayer2.Player.Next;;
        prev) qdbus-vlc org.mpris.MediaPlayer2.Player.Previous;;
    esac
else # probably playing from mpd
    case "$1" in
        seek) mpc seek "$2";;
        toggle|next|prev) mpc "$1";;
    esac
fi
