#!/bin/sh

SONG="$(mpc current)"
STATUS="$(mpc -f "%date% %album%" |
  awk 'NR==1 {print $0} NR==2 {print "<b>" $3 "</b>"}')"
if mpc status | grep '\[playing\]'; then
	PLAYING="  "
elif mpc status | grep '\[paused\]'; then
	PLAYING="  "
else
	PLAYING=""
fi

ICON=/usr/share/icons/Papirus/48x48/apps/org.gnome.music.svg
notify-send "$PLAYING$SONG" "$STATUS" -i "$ICON"
