#!/bin/sh

SONG="$(mpc current)"
TIME="$(mpc | awk 'NR==2 {print $3}')"
DATE="$(mpc -f '%originaldate%' | head -c 4)"
STATUS="$TIME $DATE <b>$(mpc -f "%album%/%track% " | head -1)</b>"
if mpc status | grep '\[playing\]'; then
	PLAYING="  "
elif mpc status | grep '\[paused\]'; then
	PLAYING="  "
else
	PLAYING=""
fi
ICON="file://$HOME/media/music/$(dirname "$(mpc -f '%file%' | head -1)")/cover.jpg"
notify-send "$PLAYING$SONG" "$STATUS" -i "$ICON"
