#!/bin/bash
# adapted from https://tex.stackexchange.com/a/199150/
#
# optpdf file.pdf
#   This script will attempt to optimize the given pdf

for file in "$@"; do
    [ ! -f "$file" ] && echo "Error: No such file $file" && exit 1
    printf "$file... "
    filebase=$(basename "$file" .pdf)
    optfile="/tmp/$$-${filebase}_opt.pdf"
    gs -sDEVICE=pdfwrite -q \
       -o "$optfile" "$file"
    [ $? != '0'  ] && echo "Non-zero gs exit code - skipping" && continue

    optsize=$(stat -c "%s" "$optfile")
    orgsize=$(stat -c "%s" "$file")
    if [ "$optsize" -eq 0 ]; then
        echo "No output!  Keeping original"
        rm -f "$optfile"
        continue;
    fi
    if [ "$optsize" -ge "$orgsize" ]; then
        echo "Didn't make it smaller! Keeping original"
        rm -f "$optfile"
        continue
    fi
    bytesSaved=$(expr $orgsize - $optsize)
    sizeSaved=$(numfmt --to iec --format "%.1f" $bytesSaved)
    percent=$(expr $optsize '*' 100 / $orgsize)
    echo saved you $sizeSaved \(now ${percent}% of old\)
    mv "$optfile" "$file"
done
