#!/bin/sh

# On 1st invocation: start recording process and save its pid to /tmp/scrrec.
# Once it is killed, remove /tmp/scrrec and notify user

# On 2nd invocation: kill the pid written in /tmp/scrrec

if [ -f /tmp/scrrec ]; then
  wf_pid="$(cat /tmp/scrrec)"
  echo "$wf_pid"
  kill -INT "$wf_pid"
  exit 0
fi


cd ~ || exit 1
region="$(slurp || exit 1)"
file="recording-$(date -Iseconds | tr ':' '!').mp4"
wf-recorder -g "$region" -f "$file" &
wf_pid=$!
echo $wf_pid >/tmp/scrrec
wait $wf_pid
rm /tmp/scrrec
notify-send "Recording finished" "$file"
