#!/bin/sh

CONSUMER_PID_FILE="/dev/shm/cpu-consumer-pid"
if [ -f $CONSUMER_PID_FILE ]; then
    CONSUMER="$(cat $CONSUMER_PID_FILE)"
    [ "$CONSUMER" = "" ] && exit
    echo "chosen cpu consumer to cont is $CONSUMER"
    notify-send "Resumed" "$CONSUMER"
    pkill -CONT "$CONSUMER"
    rm $CONSUMER_PID_FILE
else
    CONSUMER="$(ps axch -o %cpu,cmd --sort=-%cpu | rofi -i -dmenu -p 'put to sleep?' | awk '{print $2}')"
    [ "$CONSUMER" = "" ] && exit
    echo "chosen cpu consumer to stop is $CONSUMER"
    notify-send "Suspended" "$CONSUMER"
    echo "$CONSUMER" > $CONSUMER_PID_FILE
    pkill -STOP "$CONSUMER"
fi
